api/urls.py
from django.urls import path
from .views import scholarship_list, scholarship


app_name = 'api'

urlpatterns = [
    path('scholarships/', scholarship_list),
    path('<int:ronin_id>/', scholarship),
]

metamaxie_proj/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from django.conf.urls import url
from django.views.static import serve


urlpatterns = [
    url(r'^media/(?P<path>.*)$', serve,{'document_root': settings.MEDIA_ROOT}),
    url(r'^static/(?P<path>.*)$', serve,{'document_root': settings.STATIC_ROOT}),

    path('admin/', admin.site.urls),
    path('users/', include('users.urls', namespace='users')),
    path('users/', include('django.contrib.auth.urls')),
    path('profiles/', include('profiles.urls', namespace='profiles')),
    path('', include('scholarships.urls', namespace='scholarships')),  
    path('payments/', include('payments.urls', namespace='payments')),
    path('tasks/', include('tasks.urls', namespace='tasks')),
    path('api/', include('api.urls')), 
]

# if settings.DEBUG:
#     urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
#     urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

admin.site.site_header = "Metamaxie Administration"

tasks/urls.py
from django.urls import path
from . import views


app_name = 'tasks'

urlpatterns = [
    path('', views.tasks, name='tasks'),
    path('add-task1a/', views.add_task1a, name='add_task1a'),
    path('add-task1b/', views.add_task1b, name='add_task1b'),
    path('add-task12a/', views.add_task12a, name='add_task12a'),
    path('add-task12b/', views.add_task12b, name='add_task12b'),
    path('add-task123a/', views.add_task123a, name='add_task123a'),
    path('add-task123b/', views.add_task123b, name='add_task123b'),
    path('add-task1234a/', views.add_task1234a, name='add_task1234a'),
    path('edit/<int:name_id>/', views.edit_task, name='edit_task'),
    path('remove/<int:task_id>/', views.remove_task, name='remove_task'),
    path('remove-scholar/<int:scholar_id>-<int:task_id>/', views.remove_scholar_from_task, name='remove_scholar_from_task'),
    path('help-task/', views.help_task, name='help_task'),
]

tasks/models.py
from django.db import models
from users.models import ScholarTeam, User 


class Task(models.Model):
    name = models.CharField(max_length=200)
    task_1 = models.IntegerField()
    task_2 = models.IntegerField(blank=True, null=True)
    task_3 = models.IntegerField(blank=True, null=True)
    task_4 = models.IntegerField(blank=True, null=True)
    rate_1 = models.IntegerField()
    rate_2 = models.IntegerField(blank=True, null=True)
    rate_3 = models.IntegerField(blank=True, null=True)
    rate_4 = models.IntegerField(blank=True, null=True)
    rate_5 = models.IntegerField(blank=True, null=True)
    fixed_rate = models.BooleanField(default=False)
    scholar = models.ManyToManyField(ScholarTeam, blank=True)
    owner = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return str(self.name)

tasks/forms.py
from django import forms

from .models import Task
from users.models import ManagerTeam, ScholarTeam


class AddTaskForm1(forms.ModelForm):
    class Meta:
        model = Task
        fields = [
            'name',
            'task_1', 
            'rate_1',
            'fixed_rate',
            'rate_2',
            ]
        labels = {
            'name': '',
            'task_1':'',
            'rate_1':'',
            'fixed_rate':'',
            'rate_2':'',
            }


class AddTaskForm2(forms.ModelForm):
    class Meta:
        model = Task
        fields = [
            'name',
            'task_1',
            'task_2',
            'task_3',
            'task_4',
            'rate_1',
            'fixed_rate',
            'rate_2',
            'rate_3',
            'rate_4',
            'rate_5',
            ]
        labels = {
            'name':'',
            'task_1':'',
            'task_2':'',
            'task_3':'',
            'task_4':'',
            'rate_1':'',
            'fixed_rate':'',
            'rate_2':'',
            'rate_3':'',
            'rate_4':'',
            'rate_5':'',
            }


class EditTaskForm(forms.ModelForm):
    class Meta:
        model = Task
        fields = [
            'scholar',
            ]
        labels = {
            'scholar': 'scholars',
            }

    def __init__(self, *args, **kwargs):
        super(EditTaskForm, self).__init__(*args, **kwargs)
        manager = ManagerTeam.objects.get(manager=self.instance.owner)
        self.fields['scholar'].queryset = ScholarTeam.objects.filter(team_code=manager.id)
         
    scholar = forms.ModelMultipleChoiceField(
        queryset = ScholarTeam.objects.all(),
        widget=forms.CheckboxSelectMultiple
        )

tasks/views.py
from django.shortcuts import render, redirect, HttpResponseRedirect
from django.contrib.auth.decorators import login_required

from .forms import AddTaskForm1, AddTaskForm2, EditTaskForm
from .models import Task
from users.models import ScholarTeam
from scholarships.views import scholarships_table


@login_required
def tasks(request):
    '''Show all tasks'''
    tasks = Task.objects.filter(owner=request.user)
    context = {
        'tasks': tasks,
        }

    return render(request, 'tasks/tasks.html', context)


@login_required
def add_task1a(request):
    if request.method != 'POST':
        form = AddTaskForm1()
    else:
        form = AddTaskForm1(data=request.POST)
        if form.is_valid():
            add_task = form.save(commit=False)
            add_task.owner = request.user
            add_task.save()
            return redirect('tasks:add_task1b')

    tasks = Task.objects.all()
    tooltip = "You can choose a fixed amount to retain a minimum value, e.g, inputting 45 ensures to you a minimum amount of 45 SLP's.(only for this field)"

    context = {
        'form': form, 
        'tasks': tasks,
        'tooltip': tooltip,
        }
    
    return render(request, 'tasks/add_task1a.html', context)

@login_required
def add_task1b(request):
    task = Task.objects.filter(owner=request.user).last()
    name = Task.objects.get(id=task.id)
    
    if request.method != 'POST':
        form = AddTaskForm2(instance=name)
    else:
        form = AddTaskForm2(instance=name, data=request.POST)
        if form.is_valid():
            form.save()
            return redirect('tasks:add_task12a')

    context = {'name': name, 'form': form}

    return render(request, 'tasks/add_task1b.html', context)


@login_required
def add_task12a(request):
    task = Task.objects.filter(owner=request.user).last()
    name = Task.objects.get(id=task.id)
    
    if request.method != 'POST':
        form = AddTaskForm2(instance=name)
    else:
        form = AddTaskForm2(instance=name, data=request.POST)
        if form.is_valid():
            form.save()
            return redirect('tasks:add_task12b')

    context = {'name': name, 'form': form}

    return render(request, 'tasks/add_task12a.html', context)


@login_required
def add_task12b(request):
    task = Task.objects.filter(owner=request.user).last()
    name = Task.objects.get(id=task.id)
    
    if request.method != 'POST':
        form = AddTaskForm2(instance=name)
    else:
        form = AddTaskForm2(instance=name, data=request.POST)
        if form.is_valid():
            form.save()
            return redirect('tasks:add_task123a')

    context = {'name': name, 'form': form}

    return render(request, 'tasks/add_task12b.html', context)


@login_required
def add_task123a(request):
    task = Task.objects.filter(owner=request.user).last()
    name = Task.objects.get(id=task.id)
    
    if request.method != 'POST':
        form = AddTaskForm2(instance=name)
    else:
        form = AddTaskForm2(instance=name, data=request.POST)
        if form.is_valid():
            form.save()
            return redirect('tasks:add_task123b')

    context = {'name': name, 'form': form}

    return render(request, 'tasks/add_task123a.html', context)


@login_required
def add_task123b(request):
    task = Task.objects.filter(owner=request.user).last()
    name = Task.objects.get(id=task.id)
    
    if request.method != 'POST':
        form = AddTaskForm2(instance=name)
    else:
        form = AddTaskForm2(instance=name, data=request.POST)
        if form.is_valid():
            form.save()
            return redirect('tasks:add_task1234a')

    context = {'name': name, 'form': form}

    return render(request, 'tasks/add_task123b.html', context)


@login_required
def add_task1234a(request):
    task = Task.objects.filter(owner=request.user).last()
    name = Task.objects.get(id=task.id)
    
    if request.method != 'POST':
        form = AddTaskForm2(instance=name)
    else:
        form = AddTaskForm2(instance=name, data=request.POST)
        if form.is_valid():
            form.save()
            return redirect('tasks:tasks')

    context = {'name': name, 'form': form}

    return render(request, 'tasks/add_task1234a.html', context)


@login_required
def edit_task(request, name_id):
    name = Task.objects.get(id=name_id)

    if request.method != 'POST':
        form = EditTaskForm(instance=name)
    else:
        form = EditTaskForm(instance=name, data=request.POST)
        if form.is_valid():
            form.save()
            scholarships_table(request)
            return redirect('tasks:tasks')

    context = {'name': name, 'form': form}

    return render(request, 'tasks/edit_task.html', context)


@login_required
def remove_task(request, task_id):
    task = Task.objects.filter(owner=request.user).get(id=task_id)

    if request.method=='POST':
        task.delete()

        return HttpResponseRedirect('/tasks')
    
    context = {'task': task}

    return render(request, 'tasks/remove_task.html', context)


@login_required
def remove_scholar_from_task(request, scholar_id, task_id):
    scholar = ScholarTeam.objects.get(id=scholar_id)
    task = scholar.task_set.get(id=task_id)
    
    if request.method!='POST':
        task.scholar.remove(scholar)
        task.save()
        return redirect('tasks:tasks')
    

@login_required
def help_task(request):

    return render(request, 'tasks/help_task.html')

tasks/templates/tasks/add_task1234a.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title %}
    Edit Task
{% endblock %}

{% block content %}

    <h1>Rules & Sharing <a class="font-small" href="{% url 'tasks:help_task' %}">Need help?</a></h1>

    <form class="col-md-12" action="{% url 'tasks:add_task1234a' %}" method='post'>
        {% csrf_token %}

        <div class="col-md-2 mb-3">
            <label for="{{ form.name_for_label }}">rule name</label>
            {{ form.name|as_crispy_field }}
        </div>

        <div class="col-md-2 mb-3">
            <label for="{{ form.task_1_for_label }}">average smaller than</label>
            {{ form.task_1|as_crispy_field }}
        </div>

        <div class="col-md-2 mb-1">
            <label for="{{ form.rate_1_for_label }}">I receive <span class="font-small">(% or absolute value if you choose fixed - only for this field)</span></label>
            {{ form.rate_1|as_crispy_field }}
        </div>
        <div class="col-md-2 mb-3">
            <div class="d-flex flex-row bd-highlight">
                <div class="p-0 bd-highlight">
                    {{ form.fixed_rate|as_crispy_field }}
                </div>
                <div class="p-0 bd-highlight">
                    <label for="{{ form.fixed_ratefor_label }}">fixed<span 
                        type="button"
                        class="badge rounded-pill bg-secondary" 
                        data-bs-toggle="tooltip" 
                        data-bs-placement="right" 
                        title="{{ tooltip }}" >?</span>
                    </label>  
                </div>   
            </div>    
        </div>

        <div class="col-md-2 mb-3">
            <label for="{{ form.task_2_for_label }}">average greater equal than {{ name.task_1 }} and smaller than</label>
            {{ form.task_2|as_crispy_field }}
        </div>

        <div class="col-md-2 mb-3">
            <label for="{{ form.rate_2_for_label }}">I receive(%)</label>
            {{ form.rate_2|as_crispy_field }}
        </div>

        <div class="col-md-2 mb-3">
            <label for="{{ form.task_3_for_label }}">average greater equal than {{ name.task_2 }} and smaller than</label>
            {{ form.task_3|as_crispy_field }}
        </div>

        <div class="col-md-2 mb-3">
            <label for="{{ form.rate_3_for_label }}">I receive(%)</label>
            {{ form.rate_3|as_crispy_field }}
        </div>

        <div class="col-md-2 mb-3">
            <label for="{{ form.task_4_for_label }}">average greater equal than {{ name.task_3 }} and smaller than</label>
            {{ form.task_4|as_crispy_field }}
        </div>

        <div class="col-md-2 mb-3">
            <label for="{{ form.rate_4_for_label }}">I receive(%)</label>
            {{ form.rate_4|as_crispy_field }}
        </div>

        <div class="col-md-2 mb-3">
            <label for="{{ form.rate_5_for_label }}">otherwise, I receive(%)</label>
            {{ form.rate_5|as_crispy_field }}
        </div>

        <button class="btn btn-primary" name="submit">submit</button>
    </form>

{% endblock %}

{% block script %}
{% endblock %}

tasks/templates/tasks/add_task123a.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title %}
    Edit Task
{% endblock %}

{% block content %}

    <h1>Rules & Sharing <a class="font-small" href="{% url 'tasks:help_task' %}">Need help?</a></h1>

    <form class="col-md-12" action="{% url 'tasks:add_task123a' %}" method='post'>
        {% csrf_token %}

        <div class="col-md-2 mb-3">
            <label for="{{ form.name_for_label }}">rule name</label>
            {{ form.name|as_crispy_field }}
        </div>

        <div class="col-md-2 mb-3">
            <label for="{{ form.task_1_for_label }}">average smaller than</label>
            {{ form.task_1|as_crispy_field }}
        </div>

        <div class="col-md-2 mb-1">
            <label for="{{ form.rate_1_for_label }}">I receive <span class="font-small">(% or absolute value if you choose fixed - only for this field)</span></label>
            {{ form.rate_1|as_crispy_field }}
        </div>
        <div class="col-md-2 mb-3">
            <div class="d-flex flex-row bd-highlight">
                <div class="p-0 bd-highlight">
                    {{ form.fixed_rate|as_crispy_field }}
                </div>
                <div class="p-0 bd-highlight">
                    <label for="{{ form.fixed_ratefor_label }}">fixed<span 
                        type="button"
                        class="badge rounded-pill bg-secondary" 
                        data-bs-toggle="tooltip" 
                        data-bs-placement="right" 
                        title="{{ tooltip }}" >?</span>
                    </label>  
                </div>   
            </div>    
        </div>

        <div class="col-md-2 mb-3">
            <label for="{{ form.task_2_for_label }}">average greater equal than {{ name.task_1 }} and smaller than</label>
            {{ form.task_2|as_crispy_field }}
        </div>

        <div class="col-md-2 mb-3">
            <label for="{{ form.rate_2_for_label }}">I receive(%)</label>
            {{ form.rate_2|as_crispy_field }}
        </div>

        <div class="col-md-2 mb-3">
            <label for="{{ form.task_3_for_label }}">average greater equal than {{ name.task_2 }} and smaller than</label>
            {{ form.task_3|as_crispy_field }}
        </div>

        <div class="col-md-2 mb-3">
            <label for="{{ form.rate_3_for_label }}">I receive(%)</label>
            {{ form.rate_3|as_crispy_field }}
        </div>

        <div class="col-md-2 mb-3">
            <label for="{{ form.rate_4_for_label }}">otherwise, I receive(%)</label>
            {{ form.rate_4|as_crispy_field }}
        </div>

        <button class="btn btn-primary" name="submit">submit</button>
    </form>

{% endblock %}

{% block script %}
{% endblock %}

tasks/templates/tasks/add_task123b.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title %}
    Edit Task
{% endblock %}

{% block content %}

    <h1>Rules & Sharing <a class="font-small" href="{% url 'tasks:help_task' %}">Need help?</a></h1>

    <form class="col-md-12" action="{% url 'tasks:add_task123b' %}" method='post'>
        {% csrf_token %}

        <div class="col-md-2 mb-3">
            <label for="{{ form.name_for_label }}">rule name</label>
            {{ form.name|as_crispy_field }}
        </div>

        <div class="col-md-2 mb-3">
            <label for="{{ form.task_1_for_label }}">average smaller than</label>
            {{ form.task_1|as_crispy_field }}
        </div>

        <div class="col-md-2 mb-1">
            <label for="{{ form.rate_1_for_label }}">I receive <span class="font-small">(% or absolute value if you choose fixed - only for this field)</span></label>
            {{ form.rate_1|as_crispy_field }}
        </div>
        <div class="col-md-2 mb-3">
            <div class="d-flex flex-row bd-highlight">
                <div class="p-0 bd-highlight">
                    {{ form.fixed_rate|as_crispy_field }}
                </div>
                <div class="p-0 bd-highlight">
                    <label for="{{ form.fixed_ratefor_label }}">fixed<span 
                        type="button"
                        class="badge rounded-pill bg-secondary" 
                        data-bs-toggle="tooltip" 
                        data-bs-placement="right" 
                        title="{{ tooltip }}" >?</span>
                    </label>  
                </div>   
            </div>    
        </div>

        <div class="col-md-2 mb-3">
            <label for="{{ form.task_2_for_label }}">average greater equal than {{ name.task_1 }} and smaller than</label>
            {{ form.task_2|as_crispy_field }}
        </div>

        <div class="col-md-2 mb-3">
            <label for="{{ form.rate_2_for_label }}">I receive(%)</label>
            {{ form.rate_2|as_crispy_field }}
        </div>

        <div class="col-md-2 mb-3">
            <label for="{{ form.task_3_for_label }}">average greater equal than {{ name.task_2 }} and smaller than</label>
            {{ form.task_3|as_crispy_field }}
        </div>

        <div class="col-md-2 mb-3">
            <label for="{{ form.rate_3_for_label }}">I receive(%)</label>
            {{ form.rate_3|as_crispy_field }}
        </div>

        <div class="col-md-2 mb-3">
            <label for="{{ form.rate_4_for_label }}">otherwise, I receive(%)</label>
            {{ form.rate_4|as_crispy_field }}
        </div>

        <button class="btn btn-primary" name="submit">+</button>
        <a href="{% url 'tasks:tasks' %}" class="btn btn-primary" role="button">done</a>
    </form>

{% endblock %}

{% block script %}
{% endblock %}

tasks/templates/tasks/add_task12a.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title %}
    Edit Task
{% endblock %}

{% block content %}

    <h1>Rules & Sharing <a class="font-small" href="{% url 'tasks:help_task' %}">Need help?</a></h1>

    <form class="col-md-12" action="{% url 'tasks:add_task12a' %}" method='post'>
        {% csrf_token %}

        <div class="col-md-2 mb-3">
            <label for="{{ form.name_for_label }}">rule name</label>
            {{ form.name|as_crispy_field }}
        </div>

        <div class="col-md-2 mb-3">
            <label for="{{ form.task_1_for_label }}">average smaller than</label>
            {{ form.task_1|as_crispy_field }}
        </div>

        <div class="col-md-2 mb-1">
            <label for="{{ form.rate_1_for_label }}">I receive <span class="font-small">(% or absolute value if you choose fixed - only for this field)</span></label>
            {{ form.rate_1|as_crispy_field }}
        </div>
        <div class="col-md-2 mb-3">
            <div class="d-flex flex-row bd-highlight">
                <div class="p-0 bd-highlight">
                    {{ form.fixed_rate|as_crispy_field }}
                </div>
                <div class="p-0 bd-highlight">
                    <label for="{{ form.fixed_ratefor_label }}">fixed<span 
                        type="button"
                        class="badge rounded-pill bg-secondary" 
                        data-bs-toggle="tooltip" 
                        data-bs-placement="right" 
                        title="{{ tooltip }}" >?</span>
                    </label>  
                </div>   
            </div>    
        </div>

        <div class="col-md-2 mb-3">
            <label for="{{ form.task_2_for_label }}">average greater equal than {{ name.task_1 }} and smaller than</label>
            {{ form.task_2|as_crispy_field }}
        </div>

        <div class="col-md-2 mb-3">
            <label for="{{ form.rate_2_for_label }}">I receive(%)</label>
            {{ form.rate_2|as_crispy_field }}
        </div>

        <div class="col-md-2 mb-3">
            <label for="{{ form.rate_3_for_label }}">otherwise, I receive(%)</label>
            {{ form.rate_3|as_crispy_field }}
        </div>

        <button class="btn btn-primary" name="submit">submit</button>
        <!-- <a href="{% url 'tasks:tasks' %}" class="btn btn-primary" role="button">done</a> -->
    </form>

{% endblock %}

{% block script %}
{% endblock %}

tasks/templates/tasks/add_task1a.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}


{% block title %}
    Settings
{% endblock %}

{% block content %}

    {% if user.type == "MANAGER" %}

        <h1>Rules & Sharing <a class="font-small" href="{% url 'tasks:help_task' %}">Need help?</a></h1>

        <form class="col-md-12" action="{% url 'tasks:add_task1a' %}" method='post'>
            {% csrf_token %}

            <div class="col-md-2 mb-3">
                <label for="{{ form.name_for_label }}">rule name</label>
                {{ form.name|as_crispy_field }}
            </div>

            <div class="col-md-2 mb-3">
                <label for="{{ form.task_1_for_label }}">average smaller than</label>
                {{ form.task_1|as_crispy_field }}
            </div>

            <div class="col-md-2 mb-1">
                <label for="{{ form.rate_1_for_label }}">I receive <span class="font-small">(% or absolute value if you choose fixed - only for this field)</span></label>
                {{ form.rate_1|as_crispy_field }}
            </div>
            <div class="col-md-2 mb-3">
                <div class="d-flex flex-row bd-highlight">
                    <div class="p-0 bd-highlight">
                        {{ form.fixed_rate|as_crispy_field }}
                    </div>
                    <div class="p-0 bd-highlight">
                        <label for="{{ form.fixed_rate_for_label }}">fixed</label> <div 
                            type="button"
                            class="badge rounded-pill bg-secondary" 
                            data-bs-toggle="tooltip" 
                            data-bs-placement="right" 
                            title="{{ tooltip }}" >?</div>
                        </label>  
                    </div>   
                </div>    
            </div>

            <div class="col-md-2 mb-3">
                <label for="{{ form.rate_1_for_label }}">otherwise, I receive(%)</label>
                {{ form.rate_2|as_crispy_field }}
            </div>

            <button class="btn btn-primary" name="submit">submit</button>

        </form>
        
    {% else %}
        <p>oops...nothing here</p>
    {% endif %}

{% endblock %}

{% block script %}
{% endblock %}

tasks/templates/tasks/tasks.html
{% extends 'base.html' %}

{% block title %}
    Rule
{% endblock %}

{% block content %}

    {% if user.type == "MANAGER" %}

        <h1>Rules & Sharing</h1>
        <p>Decide how much you are going to pay to your scholar depending on their gain.</p>

        <a class="btn btn-primary shadow mb-3" role="button" href="{% url 'tasks:add_task1a' %}">add rule</a>

        <div class="row">
            {% for task in tasks %}
                <div class="col-sm-3">
                    <div class="card shadow rounded-10 mb-3" style="width: 18rem;">
                        <div class="card-body">     
                            <h5 class="card-title">{{ task }}</h5>
                                <div class="card-text">

                                    {% if task.task_1 != None and task.task_2 != None and task.task_3 != None and task.task_4 != None %}
                                        {% if task.fixed_rate == True %}
                                            <p class="font-small mb-0">average smaller than {{ task.task_1 }}, I receive {{ task.rate_1 }} slp's</p>
                                        {% else %}
                                            <p class="font-small mb-0">average smaller than {{ task.task_1 }}, I receive {{ task.rate_1 }}%</p>
                                        {% endif %}
                                        <p class="font-small mb-0">greater equal than {{ task.task_1 }} and smaller than {{ task.task_2 }}, I receive {{ task.rate_2 }}%</p>
                                        <p class="font-small mb-0">greater equal than {{ task.task_2 }} and smaller than {{ task.task_3 }}, I receive {{ task.rate_3 }}%</p>
                                        <p class="font-small mb-0">greater equal than {{ task.task_3 }} and smaller than {{ task.task_4 }}, I receive {{ task.rate_4 }}%</p>
                                        <p class="font-small mb-0">greater equal than {{ task.task_4 }}, I receive {{ task.rate_5 }}%</p>
                                    {% endif %}

                                    {% if task.task_1 != None and task.task_2 != None and task.task_3 != None and task.task_4 == None %}
                                        {% if task.fixed_rate == True %}
                                            <p class="font-small mb-0">average smaller than {{ task.task_1 }}, I receive {{ task.rate_1 }} slp's</p>
                                        {% else %}
                                            <p class="font-small mb-0">average smaller than {{ task.task_1 }}, I receive {{ task.rate_1 }}%</p>
                                        {% endif %}
                                        <p class="font-small mb-0">greater equal than {{ task.task_1 }} and smaller than {{ task.task_2 }}, I receive {{ task.rate_2 }}%</p>
                                        <p class="font-small mb-0">greater equal than {{ task.task_2 }} and smaller than {{ task.task_3 }}, I receive {{ task.rate_3 }}%</p>
                                        <p class="font-small mb-0">greater equal than {{ task.task_3 }}, I receive {{ task.rate_4 }}%</p>
                                    {% endif %}

                                    {% if task.task_1 != None and task.task_2 != None and task.task_3 == None and task.task_4 == None %}
                                        {% if task.fixed_rate == True %}
                                            <p class="font-small mb-0">average smaller than {{ task.task_1 }}, I receive {{ task.rate_1 }} slp's</p>
                                        {% else %}
                                            <p class="font-small mb-0">average smaller than {{ task.task_1 }}, I receive {{ task.rate_1 }}%</p>
                                        {% endif %}
                                        <p class="font-small mb-0">greater equal than {{ task.task_1 }} and smaller than {{ task.task_2 }}, I receive {{ task.rate_2 }}%</p>
                                        <p class="font-small mb-0">greater equal than {{ task.task_2 }}, I receive {{ task.rate_3 }}%</p>
                                    {% endif %}

                                    {% if task.task_1 != None and task.task_2 == None and task.task_3 == None and task.task_4 == None %}
                                        {% if task.rate_1 == task.rate_2 %}
                                            <p class="font-small mb-0">I will receive {{ task.rate_2 }}% over any amount of SLP's produced by the scholar.</p>
                                        {% else %}
                                            {% if task.fixed_rate == True %}
                                                <p class="font-small mb-0">average smaller than {{ task.task_1 }}, I receive {{ task.rate_1 }} slp's</p>
                                            {% else %}
                                                <p class="font-small mb-0">average smaller than {{ task.task_1 }}, I receive {{ task.rate_1 }}%</p>
                                            {% endif %}
                                            <p class="font-small mb-0">greater equal than {{ task.task_1 }}, I receive {{ task.rate_2 }}%</p>
                                        {% endif %}
                                    {% endif %}
                                    
                                </div><hr>
                            <h6 class="mb-1">Scholars</h6>
                            {% for scholar in task.scholar.all %}
                                <span class="badge badge-scholar rounded-pill bg-primary">{{ scholar }}
                                    <span>
                                        <a href="{% url 'tasks:remove_scholar_from_task' scholar.id task.id%}" class="link-light no-underline" data-bs-toggle="tooltip" data-bs-placement="right" title="Remove">&nbsp;&nbsp;x</a>
                                    </span>
                                </span>
                            {% endfor %}
                            <hr>
                            <a class="card-link" href="{% url 'tasks:edit_task' task.id %}">add scholar</a>
                            <a class="card-link" href="{% url 'tasks:remove_task' task.id %}">delete</a>   
                        </div>
                    </div>
                </div>
            {% empty %}
                <div class="alert alert-info" role="alert">Add rule to share SLP's with the scholar.</div>
            {% endfor %}
        </div>

    {% else %}
        <p>oops...nothing here</p>
    {% endif %}

{% endblock %}