api/urls.py
from django.urls import path
from .views import scholarship_list, scholarship


app_name = 'api'

urlpatterns = [
    path('scholarships/', scholarship_list),
    path('<int:ronin_id>/', scholarship),
]

metamaxie_proj/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from django.conf.urls import url
from django.views.static import serve


urlpatterns = [
    url(r'^media/(?P<path>.*)$', serve,{'document_root': settings.MEDIA_ROOT}),
    url(r'^static/(?P<path>.*)$', serve,{'document_root': settings.STATIC_ROOT}),

    path('admin/', admin.site.urls),
    path('users/', include('users.urls', namespace='users')),
    path('users/', include('django.contrib.auth.urls')),
    path('profiles/', include('profiles.urls', namespace='profiles')),
    path('', include('scholarships.urls', namespace='scholarships')),  
    path('payments/', include('payments.urls', namespace='payments')),
    path('tasks/', include('tasks.urls', namespace='tasks')),
    path('api/', include('api.urls')), 
]

# if settings.DEBUG:
#     urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
#     urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

admin.site.site_header = "Metamaxie Administration"

profiles/urls.py
from django.urls import path
from . import views


app_name = 'profiles'

urlpatterns = [
    path('edit/', views.edit_profile, name='edit_profile'),
    path('my/', views.my_profile, name='my_profile'),
    path('rules/', views.rules, name='rules'),
]

scholarships/urls.py
from django.contrib import admin
from django.urls import path
from scholarships import views


app_name = 'scholarships'

urlpatterns = [
    path('scholarships-table/', views.scholarships_table, name='scholarships_table'),
    path('', views.scholarships, name='scholarships_cards'),
    path('add/', views.add_scholarship, name='add_scholarship'),
    path('edit/<int:scholarship_id>/', views.edit_scholarship, name='edit_scholarship'),
    path('remove/<int:scholarship_id>/', views.remove_scholarship, name='remove_scholarship'),
    path('scholars/', views.scholars, name='scholars'),
    path('disconnect-scholar/<int:scholar_id>/', views.disconnect_scholar, name='disconnect_scholar'),
    path('refresh/', views.refresh, name='refresh'),
]

users/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from django.urls import reverse_lazy

from . import views


app_name = 'users'

urlpatterns = [
    path('register/', views.register, name='register'),
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('change-password/', views.change_password, name='change_password'),
    path('password-reset/', auth_views.PasswordResetView.as_view(
        success_url=reverse_lazy('users:password_reset_done'),
        template_name='users/password_reset.html'
        ), name='password_reset'),
    path('password-reset/done/', auth_views.PasswordResetDoneView.as_view(
        template_name='users/password_reset_sent.html'
    ), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(
        success_url=reverse_lazy('users:password_reset_complete'),
        template_name='users/password_reset_form.html'
        ), name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(
        template_name='users/password_reset_complete.html'
    ), name='password_reset_complete'),
]

users/models.py
from django.db import models
from django.conf import settings
from django.contrib.auth.models import AbstractUser
from django.urls import reverse
from django.utils.translation import gettext_lazy as _

from PIL import Image
import uuid
import os


class User(AbstractUser):

    def user_directory_path(instance, filename):
        profile_avatar_name = '{}_{}_{}/{}'.format(instance.type, instance.username, instance.id, filename)
        full_path = os.path.join(settings.MEDIA_ROOT, profile_avatar_name)

        if os.path.exists(full_path):
            os.remove(full_path)

        return profile_avatar_name
    
    class Type(models.TextChoices):
        MANAGER = 'MANAGER', 'Manager'
        SCHOLAR = 'SCHOLAR', 'Scholar'

    type = models.CharField(_('Type'), max_length=50, choices=Type.choices) # default=Type.MANAGER)
    avatar = models.ImageField(upload_to=user_directory_path, default='avatar.png')

    # make uploaded avatar squared
    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)

        if self.avatar:
            img = Image.open(self.avatar.path)

            if img.height > img.width:
                # make square by cutting off equal amounts top and bottom
                left = 0
                right = img.width
                top = (img.height - img.width)/2
                bottom = (img.height + img.width)/2
                img = img.crop((left, top, right, bottom))
                # Resize the image to 300x300 resolution
                if img.height > 300 or img.width > 300:
                    output_size = (300, 300)
                    img.thumbnail(output_size)
                    img.save(self.avatar.path)
         
            elif img.width > img.height:
                # make square by cutting off equal amounts left and right
                left = (img.width - img.height)/2
                right = (img.width + img.height)/2
                top = 0
                bottom = img.height
                img = img.crop((left, top, right, bottom))
                # Resize the image to 300x300 resolution
                if img.height > 300 or img.width >300:
                    output_size = (300, 300)
                    img.thumbnail(output_size)
                    img.save(self.avatar.path)


class ManagerManager(models.Manager):
    def get_queryset(self, *args, **kwargs):
        return super().get_queryset(*args, **kwargs).filter(type=User.Type.MANAGER)

class ScholarManager(models.Manager):
    def get_queryset(self, *args, **kwargs):
        return super().get_queryset(*args, **kwargs).filter(type=User.Type.SCHOLAR)


class ManagerTeam(models.Model):
    manager = models.OneToOneField(User, on_delete=models.CASCADE)
    team_code = models.CharField(max_length=255)

    def __str__(self):
        return str(self.team_code)

    def save(self, *args, **kwargs):
        if self.team_code=="":
            self.team_code = str(uuid.uuid4()).replace("-","").upper()[:10]
        return super().save(*args, **kwargs)

class Manager(User):
    objects = ManagerManager()

    @property
    def teamcode(self):
        return self.managerteamcode

    class Meta:
        proxy = True
    
    def save(self, *args, **kwargs):
        if not self.pk:
            self.type = User.Type.MANAGER
        return super().save(*args, **kwargs)


class ScholarTeam(models.Model):
    scholar = models.OneToOneField(User, on_delete=models.CASCADE)
    team_code = models.ForeignKey(ManagerTeam, on_delete=models.CASCADE, blank=True, null=True)
    temp_code = models.CharField(max_length=10, blank=True, null=True)

    def __str__(self):
        return str(self.scholar)

class Scholar(User):
    objects = ScholarManager()

    @property
    def teamcode(self):
        return self.scholarteamcode

    class Meta:
        proxy = True

    def save(self, *args, **kwargs):
        if not self.pk:
            self.type = User.Type.SCHOLAR
        return super().save(*args, **kwargs)

users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from .models import ScholarTeam, User

from django.shortcuts import redirect

# from allauth.account.forms import SignupForm


class LoginForm(forms.Form):
    username = forms.CharField(
        widget = forms.TextInput(
            attrs={
                'class': 'form-control'
            }
        )
    )
    password = forms.CharField(
        widget = forms.PasswordInput(
            attrs={
                'class': 'form-control'
            }
        )
    )


TYPE_CHOICES = [('MANAGER', 'Manager'), ('SCHOLAR', 'Scholar')]

class RegistrationForm(UserCreationForm):

    class Meta:
        model = User
        fields = (
            'username', 
            'email',
            'first_name',
            'last_name',
            'password1', 
            'password2',
            'type',
        )
        required = (
            'email',
            'first_name',
            'last_name',
            'type',
        )

    type = forms.ChoiceField(widget=forms.RadioSelect, choices=TYPE_CHOICES)

    def __init__(self, *args, **kwargs):
        super(RegistrationForm, self).__init__(*args, **kwargs)
        for field_name in ('username', 'email', 'password1', 'password2'):
            self.fields[field_name].help_text = ''

        for field in self.Meta.required:
            self.fields[field].required = True
        

users/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.forms import PasswordChangeForm

from .forms import LoginForm, RegistrationForm
from .models import User


def register(request):
    msg = None
    if request.method=='POST':
        form = RegistrationForm(request.POST)
        if form.is_valid():
            new_user = form.save()
            if new_user is not None and new_user.type==User.Type.MANAGER:
                login(request, new_user)
                msg = 'user created'
                return redirect('scholarships:scholarships_cards')
            if new_user is not None and new_user.type==User.Type.SCHOLAR:
                login(request, new_user)
                msg = 'user created'
                return redirect('profiles:my_profile')              
        else:
            msg = 'form is not valid'
    else:
        form = RegistrationForm()
    
    context = {'form': form, 'msg': msg}
    
    return render(request, 'users/register.html', context )



def login_view(request):
    msg = None
    form = LoginForm(request.POST or None)   
    if request.method=='POST':
        if form.is_valid():
            username = request.POST.get('username')
            password = request.POST.get('password')
            user = authenticate(username=username, password=password)
            if user is not None and user.type==User.Type.MANAGER:
                login(request, user)
                if request.GET.get('next'):
                    return redirect(request.GET.get('next'))
                else:
                    return redirect('scholarships:scholarships_cards')
            if user is not None and user.type==User.Type.SCHOLAR:
                login(request, user)
                if request.GET.get('next'):
                    return redirect(request.GET.get('next'))
                else:
                    return redirect('profiles:my_profile')
            else:
                msg = 'invalid credentials'
        else:
            msg = 'error validating form'

    context = {'form': form, 'msg': msg}

    return render(request, 'users/login.html', context)


def logout_view(request):
    logout(request)
    return redirect('users:login')


def change_password(request):
    if request.method!='POST':
        form = PasswordChangeForm(user=request.user)
    else:
        form = PasswordChangeForm(data=request.POST, user=request.user)
        if form.is_valid():
            form.save()
            login(request, form.user)
            return redirect('profiles:my_profile')
        else:
            return redirect('users:change_password')

    context = {'form': form}

    return render(request, 'users/change_password.html', context)

users/templates/users/change_password.html
{% extends 'base.html' %}
{% load bootstrap5 %}

{% block title %}
    Change password
{% endblock %}

{% block content %}

<div class="row d-flex justify-content-center align-items-center h-100">
    <div class="col col-lg-4">
        <h1>Change Password</h1>

        <form action="{% url 'users:change_password' %}" method='post'>
            {% csrf_token %}
            {% bootstrap_form form %}

            <input type="hidden" name="next" value="{% url 'profiles:my_profile' %}">
            {% buttons %}
                <button class="w-100 btn btn-primary btn-lg btn-block" name="submit">Submit</button>
            {% endbuttons %}
        </form>
    </div>
</div>

{% endblock %}

{% block script %}
{% endblock %}

users/templates/users/logged_out.html
{% extends 'base.html' %}

{% block content %}
    <p>You have been logged out.</p>
{% endblock content %}

users/templates/users/login.html
{% extends 'base.html' %}
{% load bootstrap5 %}

{% block title %}
    Login
{% endblock %}

{% block content %}

<div class="row d-flex justify-content-center align-items-center h-100">
    <div class="col col-lg-4">
        <div class="mb-3 text-center">
            <img src="/media/metamaxie_lg_01-03.svg" alt="" width="240" height="auto">
        </div>
        <p class="text-center">Don't have an account? Then please<a href="{% url 'users:register' %}"> register here</a></p>
        {% if form.errors %}
            {{ msg }}
            <p>Your username and password didn't match. PLease try again.</p>
        {% endif %}

        <form action="{% url 'users:login' %}" method='post'>
            {% csrf_token %}
            {% bootstrap_form form %}

            <input type="hidden" name="next" value="{% url 'scholarships:scholarships_table' %}">
            <p><a class="" href="{% url 'users:password_reset' %}">Forgot Password?</a></p> 
            {% buttons %}
                <button class="w-100 btn btn-primary btn-lg btn-block shadow" name="submit">Login</button>
            {% endbuttons %}
        </form>
    </div>
</div>

{% endblock %}

{% block script %}
{% endblock %}

users/templates/users/password_reset.html
{% extends 'base.html' %}
{% load bootstrap5 %}

{% block title %}
    Password reset
{% endblock %}

{% block content %}



<div class="row d-flex justify-content-center align-items-center h-100">
    <div class="col col-lg-4">
        <h1>Password reset</h1>
        <p>Forgotten your password? Enter your email address below, and we’ll email instructions for setting a new one.</p>

        <form action="{% url 'users:password_reset' %}" method='post'>
            {% csrf_token %}
            {% bootstrap_form form %}

            <!-- <input type="hidden" name="next" value="{% url 'profiles:my_profile' %}"> -->
            {% buttons %}
                <button class="w-100 btn btn-primary btn-lg btn-block" name="submit">Submit</button>
            {% endbuttons %}
        </form>
    </div>
</div>

{% endblock %}

{% block script %}
{% endblock %}

users/templates/users/password_reset_complete.html
{% extends 'base.html' %}
{% load bootstrap5 %}

{% block title %}
Password reset complete
{% endblock %}

{% block content %}

<div class="row justify-content-center align-items-center h-100">
    <div class="col col-lg-12">
        <div class="mb-3 text-center">
            <img src="/media/metamaxie-lg-01.svg" alt="" width="240" height="auto">
        </div>
        <h1>Password reset complete</h1>
        <p>Your password has been set. You may go ahead and log in now.</p>
        <p><a class="btn btn-primary" href="{% url 'users:login' %}" role="button">Login</a></p>
    </div>
</div>

{% endblock %}

{% block script %}
{% endblock %}

users/templates/users/password_reset_form.html
{% extends 'base.html' %}
{% load bootstrap5 %}

{% block title %}
    Password reset
{% endblock %}

{% block content %}

<div class="row d-flex justify-content-center align-items-center h-100">
    <div class="col col-lg-4">
        <h1>Enter new password</h1>
        <p>Please enter your new password twice so we can verify you typed it in correctly.</p>

        <form method='post'>
            {% csrf_token %}
            {% bootstrap_form form %}

            {% buttons %}
                <button class="w-100 btn btn-primary btn-lg btn-block" name="submit">Change my password</button>
            {% endbuttons %}
        </form>
    </div>
</div>

{% endblock %}

{% block script %}
{% endblock %}

users/templates/users/password_reset_sent.html
{% extends 'base.html' %}
{% load bootstrap5 %}

{% block title %}
    Password reset sent
{% endblock %}

{% block content %}

<div class="row d-flex justify-content-center align-items-center h-100">
    <div class="col col-lg-12">
        <h1>Password reset sent</h1>
        <p>We’ve emailed you instructions for setting your password, if an account exists with the email you entered. You should receive them shortly.
        If you don’t receive an email, please make sure you’ve entered the address you registered with, and check your spam folder.</p>
    </div>
</div>

{% endblock %}

{% block script %}
{% endblock %}

users/templates/users/register.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title %}
    Register
{% endblock %}

{% block content %}
<div class="row justify-content-md-center">
    <div class="col col-lg-4">
        <!-- <h1>Register</h1> -->
        <div class="mb-3 text-center">
            <img src="/media/metamaxie_lg_01-03.svg" alt="" width="240" height="auto">
        </div>
        <p class="text-center">Already have an account? Then please <a href="{% url 'users:login' %}">Login</a></p> 
        <form action="{% url 'users:register' %}" method='post'>
            {% csrf_token %}
            
            <div class="col-md-12 mb-3">
                {{ form.username|as_crispy_field }}
            </div>
    
            <div class="col-md-12 mb-3">
                {{ form.email|as_crispy_field }}
            </div>
    
            <div class="row">
                <div class="col-md-6 mb-3">
                    {{ form.first_name|as_crispy_field }}
                </div>
    
                <div class="col-md-6 mb-3">
                    {{ form.last_name|as_crispy_field }}
                </div>
            </div>
    
            <div class="col-md-12 mb-3">
                {{ form.password1|as_crispy_field }}
            </div>
    
            <div class="col-md-12 mb-3">
                {{ form.password2|as_crispy_field }}
            </div>
    
            <div class="col-md-12 mb-3">
                {{ form.type|as_crispy_field }}
            </div>
    
            <button class="w-100 btn btn-primary btn-lg btn-block shadow" name="submit">Register</button>
            <input type="hidden" name="next" value="{% url 'scholarships:scholarships_table' %}">
        </form>
    </div>
</div>

{% endblock %}

{% block script %}
{% endblock %}