api/urls.py
from django.urls import path
from .views import scholarship_list, scholarship


app_name = 'api'

urlpatterns = [
    path('scholarships/', scholarship_list),
    path('<int:ronin_id>/', scholarship),
]

metamaxie_proj/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from django.conf.urls import url
from django.views.static import serve


urlpatterns = [
    url(r'^media/(?P<path>.*)$', serve,{'document_root': settings.MEDIA_ROOT}),
    url(r'^static/(?P<path>.*)$', serve,{'document_root': settings.STATIC_ROOT}),

    path('admin/', admin.site.urls),
    path('users/', include('users.urls', namespace='users')),
    path('users/', include('django.contrib.auth.urls')),
    path('profiles/', include('profiles.urls', namespace='profiles')),
    path('', include('scholarships.urls', namespace='scholarships')),  
    path('payments/', include('payments.urls', namespace='payments')),
    path('tasks/', include('tasks.urls', namespace='tasks')),
    path('api/', include('api.urls')), 
]

# if settings.DEBUG:
#     urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
#     urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

admin.site.site_header = "Metamaxie Administration"

payments/urls.py
from django.urls import path
from . import views


app_name = 'payments'

urlpatterns = [
    path('', views.payment_view, name='payments'),
    path('scholar-table/', views.scholar_table, name='scholar_table'),
]

profiles/urls.py
from django.urls import path
from . import views


app_name = 'profiles'

urlpatterns = [
    path('edit/', views.edit_profile, name='edit_profile'),
    path('my/', views.my_profile, name='my_profile'),
    path('rules/', views.rules, name='rules'),
]

tasks/urls.py
from django.urls import path
from . import views


app_name = 'tasks'

urlpatterns = [
    path('', views.tasks, name='tasks'),
    path('add-task1a/', views.add_task1a, name='add_task1a'),
    path('add-task1b/', views.add_task1b, name='add_task1b'),
    path('add-task12a/', views.add_task12a, name='add_task12a'),
    path('add-task12b/', views.add_task12b, name='add_task12b'),
    path('add-task123a/', views.add_task123a, name='add_task123a'),
    path('add-task123b/', views.add_task123b, name='add_task123b'),
    path('add-task1234a/', views.add_task1234a, name='add_task1234a'),
    path('edit/<int:name_id>/', views.edit_task, name='edit_task'),
    path('remove/<int:task_id>/', views.remove_task, name='remove_task'),
    path('remove-scholar/<int:scholar_id>-<int:task_id>/', views.remove_scholar_from_task, name='remove_scholar_from_task'),
    path('help-task/', views.help_task, name='help_task'),
]

users/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from django.urls import reverse_lazy

from . import views


app_name = 'users'

urlpatterns = [
    path('register/', views.register, name='register'),
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('change-password/', views.change_password, name='change_password'),
    path('password-reset/', auth_views.PasswordResetView.as_view(
        success_url=reverse_lazy('users:password_reset_done'),
        template_name='users/password_reset.html'
        ), name='password_reset'),
    path('password-reset/done/', auth_views.PasswordResetDoneView.as_view(
        template_name='users/password_reset_sent.html'
    ), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(
        success_url=reverse_lazy('users:password_reset_complete'),
        template_name='users/password_reset_form.html'
        ), name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(
        template_name='users/password_reset_complete.html'
    ), name='password_reset_complete'),
]

templates/base.html
{% load static %}
{% load bootstrap5 %}
{% load crispy_forms_tags %}
{% load text_utils %}


<!doctype html>
<html lang="en">
  <head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <link rel="stylesheet" href="{% static 'style.css' %}">

    <!-- favicon --> 
    <link rel="shortcut icon" href="{% static 'favicon.ico' %}" />
    <link rel="apple-touch-icon" sizes="180x180" href="{% static 'apple-touch-icon.png' %}">
    <link rel="icon" type="image/png" sizes="32x32" href="{% static 'favicon-32x32.png' %}">
    <link rel="icon" type="image/png" sizes="16x16" href="{% static 'favicon-16x16.png' %}">

    <!-- Global site tag (gtag.js) - Google Analytics -->
    <script async src="https://www.googletagmanager.com/gtag/js?id=G-WP4ZP0XSEB"></script>
    <script>
      window.dataLayer = window.dataLayer || [];
      function gtag(){dataLayer.push(arguments);}
      gtag('js', new Date());

      gtag('config', 'G-WP4ZP0XSEB');
    </script>

    {% bootstrap_css %}
    {% bootstrap_javascript %}

  </head>

  <body class="d-flex flex-column min-vh-100">
    
        {% include 'navbar.html' %}
        {% include 'offcanvas.html' %}

    <div class="container mt-3 container py-3 h-100">
        {% block content %}
        {% endblock content %}
    </div>
        {% include 'footer.html' %}
  </body>

</html>

{% block script %}
{% endblock %}

templates/footer.html
{% if user.is_authenticated %}
<footer class="text-center text-white mt-auto" style="background-color: #0a4275;">
    <!-- Copyright -->
    <div class="p-3" style="background-color: rgba(0, 0, 0, 0.2);">
      <p class="text-white me-auto">© {% now "Y" %} Copyright - metamaxie21@gmail.com</p>
    </div>
    <!-- Copyright -->
</footer>
{% endif %}

templates/navbar.html
{% if user.is_authenticated %}
<nav class="navbar navbar-expand-lg navbar-light mb-4 py-3 border-bottom">
    <div class="container">
        {% if user.type == "MANAGER" %}
            <a class="navbar-brand" href="{% url 'scholarships:scholarships_cards' %}"><img src="/media/metamaxie_lg_01-03.svg" alt="" width="180" height="auto"></a>
        {% else %}
            <a class="navbar-brand" href="{% url 'profiles:my_profile' %}"><img src="/media/metamaxie_lg_01-03.svg" alt="" width="180" height="auto"></a>
        {% endif %}
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            {% if user.type == "MANAGER" %}
                <ul class="navbar-nav me-auto">
                    <li class="nav-item">
                        <a class="nav-link" aria-current="page" href="{% url 'scholarships:scholarships_cards' %}">Overview</a>
                    </li>

                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                          Tables
                        </a>
                        <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                          <li><a class="dropdown-item" href="{% url 'scholarships:scholarships_table' %}">Scholarships</a></li>
                          <li><a class="dropdown-item" href="{% url 'payments:payments' %}">Claims</a></li>
                        </ul>
                    </li>

                    <!-- <li class="nav-item">
                        <a class="nav-link" href="{% url 'scholarships:scholarships_table' %}">Scholarships</a>
                    </li>    
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'payments:payments' %}">Claims</a>
                    </li>         -->

                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'tasks:tasks' %}">Rules & Sharing</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" data-bs-toggle="offcanvas" href="#offcanvasExample" aria-controls="offcanvasExample">Summary</a>
                    </li>
                </ul>
                <ul class="navbar-nav ms-auto">
                    <span class="navbar-text">Hello {{ user.username }}</span>&nbsp&nbsp
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle navbar-brand" href="#" id="navbarDropdownMenuLink" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                            <img src="{{ user.avatar.url }}" alt="manager-profile" class="avatar-small">
                        </a>
                        <ul class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                            <li><a class="dropdown-item" href="{% url 'profiles:my_profile' %}">Profile</a></li>
                            <li><a class="dropdown-item" href="{% url 'scholarships:scholars' %}">Disconnect scholar</a></li>
                            <li><hr class="dropdown-divider"></li>
                            <li><a class="dropdown-item" href="{% url 'users:logout' %}">Log out</a></li>
                        </ul>
                      </li>         
                </ul>
            {% else %}
                <ul class="navbar-nav ms-auto">
                    <span class="navbar-text">Hello {{ user.username }}</span>&nbsp&nbsp
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle navbar-brand" href="#" id="navbarDropdownMenuLink" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                            <img src="{{ user.avatar.url }}" alt="manager-profile" class="avatar-small">
                        </a>
                        <ul class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                            <li><a class="dropdown-item" href="{% url 'profiles:my_profile' %}">Profile</a></li>
                            <li><a class="dropdown-item" href="{% url 'payments:scholar_table' %}">Table</a></li>
                            <li><a class="dropdown-item" href="{% url 'profiles:rules' %}">Rules</a></li>
                            <li><hr class="dropdown-divider"></li>
                            <li><a class="dropdown-item" href="{% url 'users:logout' %}">Log out</a></li>
                        </ul>
                    </li>         
                </ul>
            {% endif %}  
        </div>
    </div>
</nav>
{% endif %}

{% block content %}{% endblock content %}

templates/offcanvas.html
{% if user.is_authenticated %}
<div class="offcanvas offcanvas-start" tabindex="-1" id="offcanvasExample" aria-labelledby="offcanvasExampleLabel">
  <div class="offcanvas-header">
    <h5 class="offcanvas-title" id="offcanvasExampleLabel"></h5>
    <button type="button" class="btn-close text-reset" data-bs-dismiss="offcanvas" aria-label="Close"></button>
  </div>
  <div class="offcanvas-body">
    <ul class="list-group list-group-flush">

      <h5 class="offcanvas-title mb-1">Daily income</h5>
      <li class="list-group-item">  
        <h4 class="mb-0">${{ total_daily_slp.total_daily_fiat_earned|floatformat:2 }}</h4>
        <p class="font-small mb-0">USD earned today</p>
      </li>
      <li class="list-group-item mb-5">  
        <h4 class="mb-0">{{ total_daily_slp.total_daily_slp_earned|floatformat:0 }}</h4>
        <p class="font-small mb-0">SLP earned today</p>
      </li>  

      <h5 class="offcanvas-title mb-1">Daily outcome</h5>
      <li class="list-group-item">  
        <h4 class="mb-0">${{ total_daily_slp.total_daily_fiat_paid|floatformat:2 }}</h4>
        <p class="font-small mb-0">USD paid today</p>
      </li> 
      <li class="list-group-item mb-5">  
        <h4 class="mb-0">{{ total_daily_slp.total_daily_slp_paid|floatformat:0 }}</h4>
        <p class="font-small mb-0">SLP paid today</p>
      </li>

      <h5 class="offcanvas-title mb-1">Total income<span class="font-small">(After claim)</span></h5>
      <li class="list-group-item">  
        <h4 class="mb-0">${{ total_slp.total_fiat_earned|floatformat:2 }}</h4>
        <p class="font-small mb-0">USD earned</p>
      </li>
      <li class="list-group-item mb-5">  
        <h4 class="mb-0">{{ total_slp.total_slp_earned|floatformat:0 }}</h4>
        <p class="font-small mb-0">SLP earned</p>
      </li>  

      <h5 class="offcanvas-title mb-1">Total outcome<span class="font-small">(After claim)</span></h5>
      <li class="list-group-item">  
        <h4 class="mb-0">${{ total_slp.total_fiat_paid|floatformat:2 }}</h4>
        <p class="font-small mb-0">USD paid</p>
      </li> 
      <li class="list-group-item">  
        <h4 class="mb-0">{{ total_slp.total_slp_paid|floatformat:0 }}</h4>
        <p class="font-small mb-0">SLP paid</p>
      </li>
       
    </ul>
  </div>
</div>
{% endif %}