api/urls.py
from django.urls import path
from .views import scholarship_list, scholarship


app_name = 'api'

urlpatterns = [
    path('scholarships/', scholarship_list),
    path('<int:ronin_id>/', scholarship),
]

metamaxie_proj/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from django.conf.urls import url
from django.views.static import serve


urlpatterns = [
    url(r'^media/(?P<path>.*)$', serve,{'document_root': settings.MEDIA_ROOT}),
    url(r'^static/(?P<path>.*)$', serve,{'document_root': settings.STATIC_ROOT}),

    path('admin/', admin.site.urls),
    path('users/', include('users.urls', namespace='users')),
    path('users/', include('django.contrib.auth.urls')),
    path('profiles/', include('profiles.urls', namespace='profiles')),
    path('', include('scholarships.urls', namespace='scholarships')),  
    path('payments/', include('payments.urls', namespace='payments')),
    path('tasks/', include('tasks.urls', namespace='tasks')),
    path('api/', include('api.urls')), 
]

# if settings.DEBUG:
#     urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
#     urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

admin.site.site_header = "Metamaxie Administration"

scholarships/urls.py
from django.contrib import admin
from django.urls import path
from scholarships import views


app_name = 'scholarships'

urlpatterns = [
    path('scholarships-table/', views.scholarships_table, name='scholarships_table'),
    path('', views.scholarships, name='scholarships_cards'),
    path('add/', views.add_scholarship, name='add_scholarship'),
    path('edit/<int:scholarship_id>/', views.edit_scholarship, name='edit_scholarship'),
    path('remove/<int:scholarship_id>/', views.remove_scholarship, name='remove_scholarship'),
    path('scholars/', views.scholars, name='scholars'),
    path('disconnect-scholar/<int:scholar_id>/', views.disconnect_scholar, name='disconnect_scholar'),
    path('refresh/', views.refresh, name='refresh'),
]

scholarships/models.py
from django.db import models

from .validators import validate_ronin
from users.models import Scholar, Manager


class Ronin(models.Model):
    ronin = models.CharField(unique=True, max_length=46, validators=[validate_ronin])
    owner = models.ForeignKey(Manager, on_delete=models.CASCADE, blank=True, null=True)

    def __str__(self):
        return str(self.ronin)


class Scholarship(models.Model):
    scholarship = models.CharField(max_length=200, blank=True, null=True)
    scholar = models.ForeignKey(Scholar, on_delete=models.DO_NOTHING ,blank=True, null=True)
    ronin = models.OneToOneField(Ronin, on_delete=models.CASCADE, blank=True, null=True)
    lifetime_slp = models.IntegerField(blank=True, null=True)
    built_up_slp = models.IntegerField(blank=True, null=True)
    last_claim = models.DateTimeField(blank=True, null=True)
    total_slp = models.IntegerField(blank=True, null=True)
    in_game_slp = models.IntegerField(blank=True, null=True)
    mmr = models.BigIntegerField(blank=True, null=True)
    daily_average = models.FloatField(blank=True, null=True)
    daily_slp_earned = models.FloatField(blank=True, null=True)
    daily_slp_paid = models.FloatField(blank=True, null=True)
    daily_fiat_earned = models.FloatField(blank=True, null=True)
    daily_fiat_paid = models.FloatField(blank=True, null=True)
    next_claim = models.CharField(max_length=50, blank=True, null=True)
    owner = models.ForeignKey(Manager, on_delete=models.CASCADE, blank=True, null=True, related_name='scholarship_manager')
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return str(self.scholarship)


class TotalDailySlp(models.Model):
    total_daily_slp_earned = models.FloatField(blank=True, null=True)
    total_daily_slp_paid = models.FloatField(blank=True, null=True)
    total_daily_fiat_earned = models.FloatField(blank=True, null=True)
    total_daily_fiat_paid = models.FloatField(blank=True, null=True)
    owner = models.ForeignKey(Manager, on_delete=models.CASCADE, blank=True, null=True)

    def __str__(self):
        return str(self.owner)

        

scholarships/forms.py
from django import forms
from django.utils.translation import templatize

from .models import Scholarship, Ronin
from users.models import Scholar, ScholarTeam, ManagerTeam


class EditScholarshipForm(forms.ModelForm):
    class Meta:
        model = Scholarship
        fields = ['scholar']
        labels = {
            # 'scholar':'scholar',
            }

    def __init__(self, *args, **kwargs):
        super(EditScholarshipForm, self).__init__(*args, **kwargs)
        manager = ManagerTeam.objects.get(manager=self.instance.owner)
        scholars = list(ScholarTeam.objects.filter(team_code=manager.id))
        self.fields['scholar'].queryset = Scholar.objects.filter(username__in=scholars)


class RoninForm(forms.ModelForm):
    class Meta:
        model = Ronin
        fields = ['ronin']
        labels = {'ronin': ''}

    def __init__(self, *args, **kwargs):
        super(RoninForm, self).__init__(*args, **kwargs)
        self.fields['ronin'].widget.attrs['placeholder'] = 'ronin:xxxx...'

    def clean_ronin_address(self):
        ronin = self.cleaned_data['ronin']

        if Ronin.objects.filter(ronin=ronin).exists():
            raise forms.ValidationError('ronin address already exists.')
        return ronin





        

scholarships/views.py
import datetime
from django.shortcuts import render, redirect, get_object_or_404, HttpResponseRedirect
from django.utils import timezone
from django.contrib.auth.decorators import login_required
from django.http import Http404
from django.core import serializers

from users.models import ManagerTeam, Scholar, ScholarTeam
from .forms import EditScholarshipForm, RoninForm
from .models import Scholarship, Ronin, TotalDailySlp
from tasks.models import Task
from payments.models import Payment
from payments.views import payment_view

import pandas as pd
import numpy as np
import json
import time

from api.external_api import external_api, external_api2, currency

# Solution to get the scholarship name from mavis api
# https://graphql-gateway.axieinfinity.com/graphql?query={publicProfileWithRoninAddress(roninAddress:"ronin:RONIN_ADDRESS"){name}}

@login_required
def scholarships_table(request):

    api = external_api(request.user)
    api2 = external_api2(request.user) # fecth schplarship name absent in api

    ronins = Ronin.objects.all().filter(owner=request.user)
    ronin_list = []
    for ronin in ronins:
        ronin_list.append(ronin)

    # create scholarship names list
    temp = 'publicProfileWithRoninAddress'
    scholarships_names = []
    names_list = []
    for dict in api2:
        for key, value in dict.items():
            if temp in value:
                scholarships_names.append(value[temp])
    for key in scholarships_names:
        for value in key.values():
            names_list.append(value)

    for i in range(len(api)):
        api[i]['ronin'] = ronin_list[i]
        api[i]['name'] = names_list[i]

    for item in api:
        s = Scholarship.objects.filter(owner=request.user).get(ronin=item['ronin'])
        s.scholarship=item['name']
        s.lifetime_slp = item['lifetime_slp']
        s.last_claim = item['last_claim']
        s.total_slp = item['total_slp']
        s.in_game_slp = item['in_game_slp']
        s.built_up_slp = item['lifetime_slp'] + item['ronin_slp']
        s.mmr = item['mmr']
        s.owner = request.user
        s.save()

    qs = Scholarship.objects.all().values().filter(owner=request.user)
    if len(qs)!=0:
        df_scholarship = pd.DataFrame(qs)
        df_scholarship['now'] = timezone.now()
        df_scholarship['now'] = pd.to_datetime(df_scholarship['now'].dt.strftime('%Y-%m-%d'))
        df_scholarship['last_claim'] = pd.to_datetime(df_scholarship['last_claim'].dt.strftime('%Y-%m-%d'))
        #df_scholarship['daily_average'] = df_scholarship['in_game_slp'] / ((df_scholarship['now'] - df_scholarship['last_claim']) / np.timedelta64(1, 'D'))
        df_scholarship.loc[df_scholarship['in_game_slp']==0, 'daily_average'] = 0
        df_scholarship.loc[df_scholarship['in_game_slp']>0, 'daily_average'] = df_scholarship['in_game_slp'] / ((df_scholarship['now'] - df_scholarship['last_claim']) / np.timedelta64(1, 'D'))

        daily_average_list = df_scholarship['daily_average'].tolist()
        print('dadadadada', len(daily_average_list), daily_average_list)

        ronins = Ronin.objects.all().filter(owner=request.user)
        ronin_list = []
        for ronin in ronins:
            ronin_list.append(str(ronin))

        dict_scholarship = df_scholarship.to_dict('records')
        
        # for i in range(len(api)):
        #     api[i]['daily_average'] = daily_average_list[i]
        #     api[i]['ronin'] = ronin_list[i]

        for item in dict_scholarship:
            s, _ = Scholarship.objects.filter(owner=request.user).get_or_create(scholarship=item['scholarship'])
            s.daily_average = item['daily_average']
            s.owner = request.user
            s.save()

        manager = ManagerTeam.objects.get(manager=request.user)
        my_scholars = list(ScholarTeam.objects.filter(team_code=manager.id))
        scholars = Scholar.objects.filter(username__in=my_scholars).values()
        df_scholars = pd.DataFrame(scholars)

        df_scholars = df_scholars.rename(columns={'id': 'scholar_id'})
        
        if len(scholars)!=0:
            df_merged = pd.merge(df_scholarship[df_scholarship['scholar_id'].notna()], df_scholars, on="scholar_id")
            df_merged.rename(columns={"username": "scholar"}, inplace=True)

            # ////////////////////////////////
            # start add daily_slp_earned column

            tasks = {}
            for my_scholar in my_scholars:
                my_scholars_task = list(my_scholar.task_set.all().values_list('id'))
                my_scholars_task = str(my_scholars_task)[1:-1]
                if len(my_scholars_task)==0:
                    tasks[my_scholar.id] = '-'
                else:
                    tasks[my_scholar.id] = my_scholars_task

            df_tasks = pd.DataFrame.from_dict(tasks, orient='index', columns=['task_id'])
            df_tasks['task_id'] = df_tasks['task_id'].str.replace(r"(","").str.replace(r")","").str.replace(r",","")
            df_tasks['scholar_team_id'] = df_tasks.index
            df_tasks = df_tasks.replace('-', np.nan)
            
            try:
                df_tasks['task_id'] = df_tasks['task_id'].fillna(0).astype(int)

                scholars_team = ScholarTeam.objects.all().values()
                df_scholar_team = pd.DataFrame(scholars_team)
                df_scholar_team = df_scholar_team.rename(columns={'id': 'scholar_team_id'})
                df_merged_b = pd.merge(df_scholar_team, df_tasks, on="scholar_team_id")
                df_merged_c = pd.merge(df_merged, df_merged_b, on="scholar_id")


                for index, row in df_merged_c.iterrows():
                    if row['task_id']==0:
                        df_merged_c.loc[df_merged_c['task_id']==0, 'daily_slp_earned'] = df_merged_c['daily_average'] #round(df_merged_c['last_claim_amount']/2)
                        df_merged_c['daily_slp_paid'] = df_merged_c['daily_average'] - df_merged_c['daily_slp_earned']
                    else:
                        pc = Task.objects.get(id=row['task_id'])
                        task_1 = pc.task_1
                        task_2 = pc.task_2
                        task_3 = pc.task_3
                        task_4 = pc.task_4
                        rate_1 = pc.rate_1
                        rate_2 = pc.rate_2
                        rate_3 = pc.rate_3
                        rate_4 = pc.rate_4
                        rate_5 = pc.rate_5
                        fixed_rate = pc.fixed_rate

                        if task_1!=None and task_2==None:
                            def tasks1(task_var1, rate_var1, rate_var2, fixed_rate_var):
                                df_merged_c.loc[(df_merged_c['daily_average']<task_var1) & (df_merged_c['task_id']==row['task_id']) & (fixed_rate_var==True) & (df_merged_c['daily_average']>=rate_var1), 'daily_slp_earned'] = rate_var1
                                df_merged_c.loc[(df_merged_c['daily_average']<task_var1) & (df_merged_c['task_id']==row['task_id']) & (fixed_rate_var==True) & (df_merged_c['daily_average']<rate_var1), 'daily_slp_earned'] = df_merged_c['daily_average']
                                df_merged_c.loc[(df_merged_c['daily_average']<task_var1) & (df_merged_c['task_id']==row['task_id']) & (fixed_rate_var==False), 'daily_slp_earned'] = round(df_merged_c['daily_average'] * rate_var1/100)
                                df_merged_c.loc[(df_merged_c['daily_average']>=task_var1) & (df_merged_c['daily_average']<2000) & (df_merged_c['task_id']==row['task_id']) & (fixed_rate_var==False), 'daily_slp_earned'] = df_merged_c['daily_average'] * rate_var2/100
                            tasks1(task_1, rate_1, rate_2, fixed_rate)
                            df_merged_c['daily_slp_paid'] = df_merged_c['daily_average'] - df_merged_c['daily_slp_earned']
                        else:
                            df_merged_c.loc[(df_merged_c['daily_average']>=2000) & (df_merged_c['daily_average']<3000), 'daily_slp_earned'] = df_merged_c['daily_average'] * 50/100
                            df_merged_c.loc[(df_merged_c['daily_average']>=3000) & (df_merged_c['daily_average']<4000), 'daily_slp_earned'] = df_merged_c['daily_average'] * 50/100
                            df_merged_c.loc[df_merged_c['daily_average']>=4000, 'daily_slp_earned'] = round(df_merged_c['daily_average'] * 50/100)

                        if task_1!=None and task_2!=None and task_3==None:
                            def tasks12(task_var1, task_var2, rate_var1, rate_var2, rate_var3, fixed_rate_var):
                                df_merged_c.loc[(df_merged_c['daily_average']<task_var1) & (df_merged_c['task_id']==row['task_id']) & (fixed_rate_var==True) & (df_merged_c['daily_average']>=rate_var1), 'daily_slp_earned'] = rate_var1
                                df_merged_c.loc[(df_merged_c['daily_average']<task_var1) & (df_merged_c['task_id']==row['task_id']) & (fixed_rate_var==True) & (df_merged_c['daily_average']<rate_var1), 'daily_slp_earned'] = df_merged_c['daily_average']
                                df_merged_c.loc[(df_merged_c['daily_average']<task_var1) & (df_merged_c['task_id']==row['task_id']) & (fixed_rate_var==False), 'daily_slp_earned'] = round(df_merged_c['daily_average'] * rate_var1/100)
                                df_merged_c.loc[(df_merged_c['daily_average']>=task_var1) & (df_merged_c['daily_average']<task_var2) & (df_merged_c['task_id']==row['task_id']), 'daily_slp_earned'] = df_merged_c['daily_average'] * rate_var2/100
                                df_merged_c.loc[(df_merged_c['daily_average']>=task_var2) & (df_merged_c['daily_average']<3000) & (df_merged_c['task_id']==row['task_id']), 'daily_slp_earned'] = df_merged_c['daily_average'] * rate_var3/100
                            tasks12(task_1, task_2, rate_1, rate_2, rate_3, fixed_rate)
                            df_merged_c['daily_slp_paid'] = df_merged_c['daily_average'] - df_merged_c['daily_slp_earned']
                        else:

scholarships/templates/scholarships/add_scholarship.html
{% extends 'base.html' %}
{% load bootstrap5 %}
{% load crispy_forms_tags %}

{% block title %}
    Add Scholarship
{% endblock %}

{% block content %}

    <form action="{% url 'scholarships:add_scholarship' %}" method="post" class="form row g-3" onsubmit="myBtn.disabled = true; return true;">
        <div class="col-sm-4">
            {% csrf_token %}
            {{ form|crispy }}
        </div>
        <div class="col-auto">
            {% buttons %}
                <button name="myBtn" class="btn btn-primary">Submit</button>
            {% endbuttons %}
        </div>
    </form>

{% endblock %}

{% block script %}
{% endblock %}

scholarships/templates/scholarships/disconnect_scholar.html
{% extends 'base.html' %}
{% load bootstrap5 %}

{% block title %}
    Disconnect Scholar
{% endblock %}

{% block content %}

    <h1>{{ scholar }}</h1>

    <form method="POST">
        {% csrf_token %}
        <p>Are you sure you want to disconnect "{{ scholar }}" from your team?</p> 
        <input class="btn btn-danger" type="submit" role=button value="Yes" />
        <a class="btn btn-outline-secondary" role=button href="/scholars">Cancel </a>
    </form>

{% endblock %}

{% block script %}
{% endblock %}

scholarships/templates/scholarships/edit_scholarship.html
{% extends 'base.html' %}
{% load bootstrap5 %}

{% block title %}
    Edit Scholarship
{% endblock %}

{% block content %}

    {% if msg %}
        <div class="alert alert-info d-flex flex-row" role="alert">Please ask the scholar to create an account and then give the code below to connect them to your team. The code can be found on your profile page too.</div>
        <h3 class="fw-bold">{{ manager.team_code }}</h3> 
    {% else %}
        <h1>{{ scholarship }}</h1>

        <div class="col-4">
            <form action="{% url 'scholarships:edit_scholarship' scholarship.id %}" method='post' onsubmit="myBtn.disabled = true; return true;">
                {% csrf_token %}
                {% bootstrap_form form %}
                {% buttons %}
                    <button class="btn btn-primary" name="myBtn">Submit</button>
                {% endbuttons %}      
            </form>
        </div>
    {% endif %}

{% endblock %}

{% block script %}
{% endblock %}

scholarships/templates/scholarships/remove_scholarship.html
{% extends 'base.html' %}

{% block title %}
    Remove Scholarship
{% endblock %}

{% block content %}

    <form method="POST">
        {% csrf_token %}
        <p>Are you sure you want to delete "{{ scholarship }}" scholarship?</p> 
        <input class="btn btn-danger" type="submit" role=button value="Yes" />
        <a class="btn btn-outline-secondary" role=button href="/">Cancel </a>
    </form>

{% endblock %}

{% block script %}
{% endblock %}

scholarships/templates/scholarships/scholars.html
{% extends 'base.html' %}

{% block title %}
    Scholars
{% endblock %}

{% block content %}

    {% if user.type == "MANAGER" %}

    <h1>Scholars</h1>
    <p>You have <strong>{{ scholars|length }}</strong> scholars in your team.</p>

    {% for scholar in scholars|dictsort:"scholar.first_name"  %}

        <ul class="list-group list-group-flush">      
            <li class="list-group-item">
                    <p class="mb-0"><strong>{{ scholar }}</strong></p>
                    <p class="mb-0">{{ scholar.scholar.first_name }} {{ scholar.scholar.last_name}}</p>
                    <a href="{% url 'scholarships:disconnect_scholar' scholar.id %}" role="button">Disconnect</a>
            </li>      
        </ul><hr>
        
        
    {% endfor %}

    

        

    {% else %}
        <p>oops...nothing here</p>
    {% endif %}

{% endblock %}

{% block script %}


{% endblock %}

scholarships/templates/scholarships/scholarships_cards.html
{% extends 'base.html' %}
{% load text_utils %}

{% block title %}
    Scholarships
{% endblock %}

{% block content %}

    {% if user.type == "MANAGER" %}

        {% if msg %}
            <div class="alert alert-danger" role="alert">{{ msg }}</div>        
        {% endif %}

        <div class="d-flex flex-row">
            <div class="p-2">
                <a href="{% url 'scholarships:add_scholarship' %}" class="btn btn-primary shadow mb-3" role="button">add scholarship</a>
            </div>
            <div class="p-2">
                <a href="{% url 'scholarships:refresh' %}" class="btn btn-outline-success mb-3" role="button">refresh</a>
            </div>
            <div class="col-sm-4 mb-3">
                <!-- <input id="search_here" class="form-control" placeholder="type here to search..."> -->
            </div>      
        </div>     
        <div class="row" id="box">
            {% for scholarship in scholarships %}
                <div class="col-sm-3">
                    <div class="card shadow rounded-10 mb-5" style="width: 20rem;">
                        <div class="card-body">
                            <h4 class="card-title">{{ scholarship|truncatechars_middle:20 }}</h4>
                            <h6 class="card-subtitle mb-2 text-muted font-nano">{{ scholarship.ronin }}</h6><hr>                 
                            <ul class="list-group list-group-flush">
                                <li class="list-group-item"><h4 class="mb-0">{{ scholarship.scholar.first_name|default:"None"|truncatechars:10|title }} {{ scholarship.scholar.last_name|truncatechars:10|title }}</h4><p class="text-secondary font-small mb-1">scholar</p></li>
                            </ul><hr class="mt-0">
                            <div class="row">
                                <div class="col">
                                    <ul class="list-group list-group-flush">
                                        <li class="list-group-item"><h4 class="mb-0">{{ scholarship.mmr }}</h4><p class="text-secondary font-small mb-1">mmr</p></li>
                                        <li class="list-group-item"><h4 class="mb-0">{{ scholarship.built_up_slp }}</h4><p class="text-secondary font-small mb-1">built up SLP</p></li>
                                        <li class="list-group-item"><h4 class="mb-0">{{ scholarship.daily_slp_earned|floatformat:0 }}</h4><p class="text-secondary font-small mb-1">daily earnings</p></li>
                                    </ul>
                                </div>
                                <div class="col">
                                    <ul class="list-group list-group-flush">
                                        <li class="list-group-item"><h4 class="mb-0">{{ scholarship.in_game_slp }}</h4><p class="text-secondary font-small mb-1">in game SLP</p></li>
                                        <li class="list-group-item"><h4 class="mb-0">{{ scholarship.daily_average|floatformat:0 }}</h4><p class="text-secondary font-small mb-1">daily average</p></li>
                                        <li class="list-group-item"><h4 class="mb-0">{{ scholarship.next_claim }}</h4><p class="text-secondary font-small mb-1">to the next claim</p></li>
                                    </ul>
                                </div>
                            </div>
                        </div>
                        <div class="card-body">
                            <a href="{% url 'scholarships:edit_scholarship' scholarship.id %}" class="card-link">Assign a scholar</a>
                            <a href="{% url 'scholarships:remove_scholarship' scholarship.id %}" class="card-link" >Delete</a>
                        </div> 
                    </div>                  
                </div>
            
            {% empty %}
                <div class="alert alert-info" role="alert">No scholarships have been added yet.</div> 
            {% endfor %}
        </div>

    {% else %}
        <p>oops...nothing here</p>
    {% endif %}

{% endblock %}

{% block script %}

    <!-- <script>
        const data = '{{ scholarships_json }}'
        console.log(data)

        const rdata = JSON.parse(data.replace(/&quot;/g, '"'))
        console.log(rdata)

        const input = document.getElementById('search_here')
        console.log(input)

        let filteredArr = []

        input.addEventListener('keyup', (e)=>{
            box.innerHTML = ""
            filteredArr = rdata.filter(info=> info['scholarship'].includes(e.target.value))
            console.log(filteredArr)
            if (filteredArr.length>0){
                filteredArr.map(info=>{
                    box.innerHTML += `${info['scholarship']}`
                })
            } else {
                box.innerHTML = 'No results found...'
            }

        })
    </script> -->


{% endblock %}

scholarships/templates/scholarships/scholarships_table.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title %}
    Scholarship
{% endblock %}

{% block content %}

    {% if user.type == "MANAGER" %}

        <h1>Scholarships</h1>
        {% if msg1 %}
            <div class="alert alert-info" role="alert">{{ msg1 }}</div>
        {% elif msg2 %}
            <div class="p-2">
                <div class="alert alert-info" role="alert">{{ msg2 }}</div>
                <a href="{% url 'scholarships:add_scholarship' %}" class="btn btn-primary shadow mb-3" role="button">add scholarship</a>
            </div>
        {% elif msg3 %}
            <div class="alert alert-warning" role="alert">{{ msg3 }}</div>  
        {% endif %}

        <!-- <p>df_scholarship</p>
        {{ df_scholarship | safe }}

        <p>df_scholars</p>
        {{ df_tasks | safe }}

        <p>df_merged</p>
        {{ df_merged | safe }}

        <p>df_tasks</p>
        {{ df_tasks | safe }}

        <p>df_scholar_team</p>
        {{ df_scholar_team | safe }}

        <p>df_merged_b</p>
        {{ df_merged_b | safe }}
        
        <p>df_merged_c</p>
        {{ df_merged_c | safe }}

        <p>df</p> -->
        {{ df | safe }}

        
    {% else %}
        <p>oops...nothing here</p>
    {% endif %}
    
{% endblock %}



{% block script %}
{% endblock %}